export const REGION_MAP: Record<string, string[]> = {
  Africa: [
    "Algeria",
    "Botswana",
    "Egypt",
    "Ethiopia",
    "Ghana",
    "Kenya",
    "Morocco",
    "Nigeria",
    "South Africa",
    "Tunisia",
    "Uganda",
  ],
  "Arab Region": [
    "Algeria",
    "Bahrain",
    "Egypt",
    "Iraq",
    "Jordan",
    "Kuwait",
    "Lebanon",
    "Morocco",
    "Oman",
    "Qatar",
    "Saudi Arabia",
    "Tunisia",
    "United Arab Emirates",
  ],
  Asia: [
    "Bangladesh",
    "Brunei",
    "China",
    "Hong Kong",
    "India",
    "Indonesia",
    "Japan",
    "Kazakhstan",
    "Macau",
    "Malaysia",
    "Pakistan",
    "Philippines",
    "Singapore",
    "South Korea",
    "Taiwan",
    "Thailand",
    "Vietnam",
  ],
  Europe: [
    "Austria",
    "Belgium",
    "Czech Republic",
    "Denmark",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Russia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "United Kingdom",
  ],
  "Latin America": [
    "Argentina",
    "Brazil",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Ecuador",
    "Mexico",
    "Peru",
    "Uruguay",
    "Venezuela",
  ],
  "North America": [
    "Canada",
    "Mexico",
    "Puerto Rico",
    "United States",
  ],
  Oceania: [
    "Australia",
    "New Zealand",
  ],
};

export function normalizeCountryName(country: string): string {
  return country.trim().replace(/\s+/g, " ");
}

export function countryBelongsToRegion(country: string, region: string): boolean {
  const normalizedCountry = normalizeCountryName(country);
  const regionCountries = REGION_MAP[region] ?? [];
  return regionCountries.includes(normalizedCountry);
}
