/*
 * test_weakness.c
 *
 * Weakness-driven regression tests for the Clawer C Data Normalization Engine.
 *
 * This file was generated by systematic weakness analysis (2026-04-13).
 *
 * Weaknesses targeted:
 *   W1.  rank_parser  — =N  format silently returns -1/-1 (未定義行為)
 *   W2.  rank_parser  — N+  format silently returns -1/-1 (未定義行為)
 *   W3.  rank_parser  — #N  hash prefix format (e.g., "#10") — fixed in Session 2
 *   W4.  rank_parser  — integer overflow for extremely large rank values
 *   W5.  score_parser — negative score ambiguity: -1.0 sentinel vs real value
 *   W6.  score_parser — score with trailing garbage (e.g., "91.2 pts")
 *   W7.  name_normalizer — ampersand (&) in university names
 *   W8.  name_normalizer — slash (/) separator in names
 *   W9.  country_normalizer — major countries not in explicit alias table
 *   W10. csv_writer   — score exactly -1.0 is suppressed as blank
 *   W11. csv_writer   — rank_min > rank_max (inverted) not validated
 *   W12. csv_reader   — empty CSV (header only, no data rows)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "normalizer.h"
#include "record.h"
#include "csv_reader.h"
#include "csv_writer.h"

/* ------------------------------------------------------------------ */
/*  Minimal test harness                                               */
/* ------------------------------------------------------------------ */

static int g_run    = 0;
static int g_pass   = 0;
static int g_fail   = 0;

static void chk(const char *label, int ok,
                const char *actual, const char *expected)
{
    g_run++;
    if (ok) {
        g_pass++;
        printf("[PASS] %s\n", label);
    } else {
        g_fail++;
        printf("[FAIL] %s\n", label);
        if (actual && expected)
            printf("       expected: \"%s\"\n       actual:   \"%s\"\n",
                   expected, actual);
    }
}

static int write_temp_file(const char *path, const char *content)
{
    FILE *fp = fopen(path, "w");
    if (!fp) return 0;
    fputs(content, fp);
    return fclose(fp) == 0;
}

static int read_temp_file(const char *path, char *buf, size_t size)
{
    FILE *fp = fopen(path, "r");
    size_t n;
    if (!fp) return 0;
    n = fread(buf, 1, size - 1, fp);
    buf[n] = '\0';
    fclose(fp);
    return 1;
}

/* ------------------------------------------------------------------ */
/*  W1: rank =N format (e.g., "=201")                                 */
/* ------------------------------------------------------------------ */

static void test_w1_rank_equals_prefix(void)
{
    int mn, mx;

    printf("\n--- W1: rank =N format ---\n");

    parse_rank("=201", &mn, &mx);
    chk("W1: \"=201\" -> 201/201 (fix: equals prefix = exact rank)",
        mn == 201 && mx == 201, NULL, NULL);

    parse_rank("=1", &mn, &mx);
    chk("W1: \"=1\" -> 1/1",
        mn == 1 && mx == 1, NULL, NULL);

    parse_rank("=500", &mn, &mx);
    chk("W1: \"=500\" -> 500/500",
        mn == 500 && mx == 500, NULL, NULL);

    /* Leading spaces must still work */
    parse_rank("  =99  ", &mn, &mx);
    chk("W1: \"  =99  \" -> 99/99 (trimmed)",
        mn == 99 && mx == 99, NULL, NULL);
}

/* ------------------------------------------------------------------ */
/*  W2: rank N+ format (e.g., "201+")                                 */
/* ------------------------------------------------------------------ */

static void test_w2_rank_plus_suffix(void)
{
    int mn, mx;

    printf("\n--- W2: rank N+ format ---\n");

    parse_rank("201+", &mn, &mx);
    chk("W2: \"201+\" -> 201/201 (fix: plus suffix = open floor rank)",
        mn == 201 && mx == 201, NULL, NULL);

    parse_rank("501+", &mn, &mx);
    chk("W2: \"501+\" -> 501/501",
        mn == 501 && mx == 501, NULL, NULL);

    parse_rank("1+", &mn, &mx);
    chk("W2: \"1+\" -> 1/1",
        mn == 1 && mx == 1, NULL, NULL);

    /* Spaces before number */
    parse_rank("  100+", &mn, &mx);
    chk("W2: \"  100+\" -> 100/100 (trimmed)",
        mn == 100 && mx == 100, NULL, NULL);
}

/* ------------------------------------------------------------------ */
/*  W3: rank #N format (e.g., "#10")                                  */
/* ------------------------------------------------------------------ */

static void test_w3_rank_hash_prefix(void)
{
    int mn, mx;

    printf("\n--- W3: rank #N format ---\n");

    /*
     * Fix C (Session 2): #N hash-prefix format is now supported.
     * "#10" should parse to rank_min=10, rank_max=10.
     */
    parse_rank("#10", &mn, &mx);
    chk("W3: \"#10\" parses to 10/10 (fixed in Session 2)",
        mn == 10 && mx == 10, NULL, NULL);

    parse_rank("#1", &mn, &mx);
    chk("W3: \"#1\" parses to 1/1",
        mn == 1 && mx == 1, NULL, NULL);
}

/* ------------------------------------------------------------------ */
/*  W4: rank integer overflow                                          */
/* ------------------------------------------------------------------ */

static void test_w4_rank_overflow(void)
{
    int mn, mx;

    printf("\n--- W4: rank integer overflow ---\n");

    /*
     * Value that fits in int: must parse correctly.
     */
    parse_rank("2000000", &mn, &mx);
    chk("W4: \"2000000\" fits in int -> 2000000/2000000",
        mn == 2000000 && mx == 2000000, NULL, NULL);

    /*
     * Overflow-inducing string. sscanf with %d on overflow is undefined
     * behaviour; this test verifies the engine does NOT crash and returns
     * something (we don't assert a specific value, only no crash).
     */
    parse_rank("99999999999999", &mn, &mx);
    chk("W4: \"99999999999999\" overflow does not crash",
        1 /* no crash == pass */, NULL, NULL);
    printf("       INFO: overflow result -> min=%d max=%d"
           "  (UB territory; crash = test failure)\n", mn, mx);
}

/* ------------------------------------------------------------------ */
/*  W5: score_parser negative score ambiguity                         */
/* ------------------------------------------------------------------ */

static void test_w5_score_negative_ambiguity(void)
{
    double s;

    printf("\n--- W5: score negative value ambiguity ---\n");

    /*
     * -1.0 as input: currently parsed as -1.0, indistinguishable from
     * the "no data" sentinel. This is a DESIGN WEAKNESS: data loss for
     * the edge case where a legitimate score equals -1.0 exactly.
     */
    s = parse_score("-1.0");
    printf("       INFO: parse_score(\"-1.0\") -> %.4f"
           "  (sentinel collision: -1.0 == invalid marker)\n", s);
    chk("W5: parse_score(\"-1.0\") returns -1.0 (ambiguous — documented)",
        s > -1.001 && s < -0.999, NULL, NULL);

    /*
     * -2.5: any negative score is treated as invalid by csv_writer
     * (score < 0 outputs blank). Verify the writer does suppress it.
     */
    {
        const char *filename = "build/test_w5_neg_score.csv";
        char buf[512];
        UniversityRecord rec;
        memset(&rec, 0, sizeof(rec));
        strcpy(rec.normalized_name, "Test University");
        strcpy(rec.normalized_country, "Unknown");
        rec.rank_min = 1;
        rec.rank_max = 1;
        rec.score = -2.5;   /* legitimate but negative */

        if (!write_normalized_csv(filename, &rec, 1) ||
            !read_temp_file(filename, buf, sizeof(buf))) {
            chk("W5: csv_writer suppresses negative score (file I/O failed)", 0, NULL, NULL);
        } else {
            /*
             * The CSV row should end with a blank score field (just comma
             * and newline after rank_max).
             */
            chk("W5: csv_writer silently suppresses score -2.5 as blank",
                strstr(buf, "1,1,\n") != NULL, buf, "...1,1,\\n");
        }
        remove(filename);
    }

    /*
     * Score of 0.0: must NOT be suppressed.
     */
    {
        const char *filename = "build/test_w5_zero_score.csv";
        char buf[512];
        UniversityRecord rec;
        memset(&rec, 0, sizeof(rec));
        strcpy(rec.normalized_name, "Zero Score Univ");
        strcpy(rec.normalized_country, "Unknown");
        rec.rank_min = 5;
        rec.rank_max = 5;
        rec.score = 0.0;

        if (!write_normalized_csv(filename, &rec, 1) ||
            !read_temp_file(filename, buf, sizeof(buf))) {
            chk("W5: csv_writer preserves score 0.0 (file I/O failed)", 0, NULL, NULL);
        } else {
            chk("W5: csv_writer preserves score 0.0 (not suppressed)",
                strstr(buf, "0.00") != NULL, buf, "...0.00...");
        }
        remove(filename);
    }
}

/* ------------------------------------------------------------------ */
/*  W6: score with trailing garbage                                   */
/* ------------------------------------------------------------------ */

static void test_w6_score_trailing_garbage(void)
{
    double s;

    printf("\n--- W6: score trailing garbage ---\n");

#define NEAR(v, t) ((v) > (t) - 0.001 && (v) < (t) + 0.001)

    s = parse_score("91.2 pts");
    chk("W6: \"91.2 pts\" -> 91.2 (stops at space)",
        NEAR(s, 91.2), NULL, NULL);

    s = parse_score("85/100");
    chk("W6: \"85/100\" -> 85 (stops at slash)",
        NEAR(s, 85.0), NULL, NULL);

    s = parse_score("73.5%");
    chk("W6: \"73.5%\" -> 73.5 (stops at percent)",
        NEAR(s, 73.5), NULL, NULL);

    s = parse_score("Score=90.0");
    chk("W6: \"Score=90.0\" -> 90.0 (first numeric substring)",
        NEAR(s, 90.0), NULL, NULL);

#undef NEAR
}

/* ------------------------------------------------------------------ */
/*  W7: ampersand in university name                                   */
/* ------------------------------------------------------------------ */

static void test_w7_name_ampersand(void)
{
    char out[NAME_LEN];

    printf("\n--- W7: ampersand in name ---\n");

    /*
     * '&' is punctuation per ispunct(). name_normalizer's
     * normalize_name_punctuation only strips '.' and replaces ',;:',
     * so '&' should pass through unchanged.
     */
    normalize_name("Arts & Sciences University", out, NAME_LEN);
    chk("W7: '&' preserved in name (not stripped)",
        strstr(out, "&") != NULL, out, "(contains &)");

    normalize_name("Science & Engineering Institute", out, NAME_LEN);
    chk("W7: \"Science & Engineering Institute\" preserves &",
        strcmp(out, "Science & Engineering Institute") == 0,
        out, "Science & Engineering Institute");

    /* Leading & trailing & */
    normalize_name("& Technology", out, NAME_LEN);
    chk("W7: \"& Technology\" -> \"& Technology\" (& kept at start)",
        strcmp(out, "& Technology") == 0, out, "& Technology");
}

/* ------------------------------------------------------------------ */
/*  W8: slash in university name                                       */
/* ------------------------------------------------------------------ */

static void test_w8_name_slash(void)
{
    char out[NAME_LEN];

    printf("\n--- W8: slash in name ---\n");

    /*
     * Slash is punctuation. normalize_name_punctuation does not handle it
     * explicitly, so it passes through. Verify this behaviour.
     */
    /*
     * Fix applied: '/' now triggers capitalize_next = 1 in apply_readable_name_case,
     * so the character immediately after '/' is capitalised.
     * Before fix: "X/Y" -> "X/y"
     * After  fix: "X/Y" -> "X/Y"
     */
    normalize_name("University of X/Y Campus", out, NAME_LEN);
    chk("W8: slash passes through, char after slash capitalised (fix verified)",
        strcmp(out, "University of X/Y Campus") == 0, out, "University of X/Y Campus");

    normalize_name("Arts/Sciences Department", out, NAME_LEN);
    chk("W8: \"Arts/Sciences\" -> \"Arts/Sciences\" (S after slash capitalised)",
        strcmp(out, "Arts/Sciences Department") == 0, out, "Arts/Sciences Department");
}

/* ------------------------------------------------------------------ */
/*  W9: countries not in explicit alias table                         */
/* ------------------------------------------------------------------ */

static void test_w9_country_fallback_major(void)
{
    char out[COUNTRY_LEN];

    printf("\n--- W9: major countries via title-case fallback ---\n");

    normalize_country("japan", out, COUNTRY_LEN);
    chk("W9: \"japan\" -> \"Japan\" (title-case fallback)",
        strcmp(out, "Japan") == 0, out, "Japan");

    normalize_country("GERMANY", out, COUNTRY_LEN);
    chk("W9: \"GERMANY\" -> \"Germany\"",
        strcmp(out, "Germany") == 0, out, "Germany");

    normalize_country("france", out, COUNTRY_LEN);
    chk("W9: \"france\" -> \"France\"",
        strcmp(out, "France") == 0, out, "France");

    normalize_country("canada", out, COUNTRY_LEN);
    chk("W9: \"canada\" -> \"Canada\"",
        strcmp(out, "Canada") == 0, out, "Canada");

    normalize_country("switzerland", out, COUNTRY_LEN);
    chk("W9: \"switzerland\" -> \"Switzerland\"",
        strcmp(out, "Switzerland") == 0, out, "Switzerland");

    normalize_country("sweden", out, COUNTRY_LEN);
    chk("W9: \"sweden\" -> \"Sweden\"",
        strcmp(out, "Sweden") == 0, out, "Sweden");

    normalize_country("netherlands", out, COUNTRY_LEN);
    chk("W9: \"netherlands\" -> \"Netherlands\"",
        strcmp(out, "Netherlands") == 0, out, "Netherlands");

    normalize_country("belgium", out, COUNTRY_LEN);
    chk("W9: \"belgium\" -> \"Belgium\"",
        strcmp(out, "Belgium") == 0, out, "Belgium");

    /*
     * Idempotency: title-case output run through normalizer again.
     */
    normalize_country("Japan", out, COUNTRY_LEN);
    chk("W9: idempotent - \"Japan\" -> \"Japan\"",
        strcmp(out, "Japan") == 0, out, "Japan");

    normalize_country("Germany", out, COUNTRY_LEN);
    chk("W9: idempotent - \"Germany\" -> \"Germany\"",
        strcmp(out, "Germany") == 0, out, "Germany");
}

/* ------------------------------------------------------------------ */
/*  W10: csv_writer rank_min > rank_max (inverted range)              */
/* ------------------------------------------------------------------ */

static void test_w10_writer_inverted_rank(void)
{
    const char *filename = "build/test_w10_inverted_rank.csv";
    char buf[512];
    UniversityRecord rec;

    printf("\n--- W10: csv_writer inverted rank (min > max) ---\n");

    memset(&rec, 0, sizeof(rec));
    strcpy(rec.normalized_name, "Inverted Rank University");
    strcpy(rec.normalized_country, "France");
    rec.rank_min = 150;
    rec.rank_max = 100;   /* inverted: min > max */
    rec.score = 75.0;

    if (!write_normalized_csv(filename, &rec, 1) ||
        !read_temp_file(filename, buf, sizeof(buf))) {
        chk("W10: inverted rank written without crash (file I/O failed)", 0, NULL, NULL);
        return;
    }

    /*
     * csv_writer writes values as-is. No validation. Verifying the
     * values appear in output documents current behaviour.
     */
    chk("W10: inverted rank (150,100) written without crash",
        strstr(buf, "150,100") != NULL, buf, "...150,100...");
    printf("       INFO: csv_writer does NOT validate rank order — design gap.\n");
    remove(filename);
}

/* ------------------------------------------------------------------ */
/*  W11: csv_reader empty file (header only)                          */
/* ------------------------------------------------------------------ */

static void test_w11_reader_empty_data(void)
{
    const char *filename = "build/test_w11_empty.csv";
    UniversityRecord records[4];
    int count;

    printf("\n--- W11: csv_reader empty file (header only) ---\n");

    if (!write_temp_file(filename,
            "University,Country,Rank Min,Rank Max,Overall Score\n")) {
        chk("W11: header-only CSV returns 0 records (file I/O failed)", 0, NULL, NULL);
        remove(filename);
        return;
    }

    count = load_csv_data(filename, records, 4);
    chk("W11: header-only CSV -> 0 records (no crash)",
        count == 0, NULL, NULL);
    remove(filename);
}

/* ------------------------------------------------------------------ */
/*  W12: csv_reader UTF-8 BOM in header                               */
/* ------------------------------------------------------------------ */

static void test_w12_reader_bom(void)
{
    const char *filename = "build/test_w12_bom.csv";
    UniversityRecord records[4];
    int count;
    /*
     * UTF-8 BOM (EF BB BF) prepended to the header line.
     */
    const char bom_csv[] =
        "\xef\xbb\xbf"
        "University,Country,Rank Min,Rank Max,Overall Score\n"
        "MIT,United States,1,1,98.4\n";

    printf("\n--- W12: UTF-8 BOM in CSV header ---\n");

    if (!write_temp_file(filename, bom_csv)) {
        chk("W12: BOM-prefixed CSV loads correctly (file I/O failed)", 0, NULL, NULL);
        remove(filename);
        return;
    }

    count = load_csv_data(filename, records, 4);
    chk("W12: BOM-prefixed CSV loads 1 record",
        count == 1, NULL, NULL);
    if (count == 1) {
        chk("W12: first record name is \"MIT\"",
            strcmp(records[0].raw_name, "MIT") == 0,
            records[0].raw_name, "MIT");
    }
    remove(filename);
}

/* ------------------------------------------------------------------ */
/*  Integration: full pipeline with newly supported rank formats       */
/* ------------------------------------------------------------------ */

static void test_integration_new_rank_formats(void)
{
    const char *filename = "build/test_integration_ranks.csv";
    UniversityRecord records[10];
    int count;
    const char *csv_content =
        "University,Country,Rank Min,Rank Max,Overall Score\n"
        "Alpha University,usa,=201,=201,88.0\n"
        "Beta University,uk,201+,201+,85.0\n"
        "Gamma University,sg,1,1,99.0\n";

    printf("\n--- Integration: pipeline with =N and N+ rank formats ---\n");

    if (!write_temp_file(filename, csv_content)) {
        chk("integration: load CSV with =N / N+ ranks (file I/O failed)", 0, NULL, NULL);
        return;
    }

    count = load_csv_data(filename, records, 10);
    chk("integration: 3 records loaded", count == 3, NULL, NULL);

    if (count == 3) {
        normalize_dataset(records, count);

        /* Record 0: =201-=201 raw_rank -> parse_rank("=201-=201") */
        chk("integration: =201-=201 parsed to 201/201",
            records[0].rank_min == 201 && records[0].rank_max == 201,
            NULL, NULL);

        /* Record 1: 201+-201+ raw_rank -> parse_rank("201+-201+") */
        chk("integration: 201+-201+ parsed to 201/201",
            records[1].rank_min == 201 && records[1].rank_max == 201,
            NULL, NULL);

        /* Record 2: control row */
        chk("integration: 1-1 parsed correctly",
            records[2].rank_min == 1 && records[2].rank_max == 1,
            NULL, NULL);

        chk("integration: country usa -> United States",
            strcmp(records[0].normalized_country, "United States") == 0,
            records[0].normalized_country, "United States");
    }
    remove(filename);
}

/* ------------------------------------------------------------------ */
/*  main                                                               */
/* ------------------------------------------------------------------ */

int main(void)
{
    printf("==== WEAKNESS-DRIVEN REGRESSION TESTS ====\n");
    printf("     Generated: 2026-04-13\n");

    test_w1_rank_equals_prefix();
    test_w2_rank_plus_suffix();
    test_w3_rank_hash_prefix();
    test_w4_rank_overflow();
    test_w5_score_negative_ambiguity();
    test_w6_score_trailing_garbage();
    test_w7_name_ampersand();
    test_w8_name_slash();
    test_w9_country_fallback_major();
    test_w10_writer_inverted_rank();
    test_w11_reader_empty_data();
    test_w12_reader_bom();
    test_integration_new_rank_formats();

    printf("\n==== WEAKNESS TEST SUMMARY ====\n");
    printf("Passed: %d / %d\n", g_pass, g_run);
    if (g_fail > 0) {
        printf("FAILED: %d test(s) — see above for details.\n", g_fail);
        return 1;
    }
    printf("All weakness tests passed.\n");
    return 0;
}
